#/bin/bash

FILENAME=$1

mv $FILENAME.BOL CAM/
mv $FILENAME.dri CAM/
mv $FILENAME.FDR CAM/
mv $FILENAME.GB* CAM/
mv $FILENAME.GT* CAM/
mv $FILENAME.GM* CAM/
mv $FILENAME.TXT CAM/
mv $FILENAME.gpi CAM/
